site_name: Siad Pdf Compressor
theme:
  name: material
  language: it
  highlightjs: true
  palette:
    primary: 'cyan'
copyright: "Siad Pdf Compressor application: Copyright 2021-2025 &copy; Cristiano Cinotti <a href='https://github.com/susina/psr2-code-generator/blob/master/LICENSE'>Apache2 license</a></br>Documentation: Copyright 2025 &copy; Cristiano Cinotti <a href='https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1'>CC BY 4.0</a>"
repo_name: 'cristianc72/siad-pdf-compressor/'
repo_url: 'https://github.com/cristianoc72/siad-pdf-compressor'
markdown_extensions:
  - admonition
  - codehilite
nav:
  - Home: index.md
  - Documentazione:
    - Installazione: installation.md
    - "Guida all'uso": user_guide.md
  - Contribuire: contributing.md
  - Licenza: license.md
  